server:
  live:
    port: 1989
    url: "http://localhost:1989"
    full_picture_interval: 3 #in seconds
    debug: true
    vue_version: "2.6.12"
    ice_config:
      dynamic_credential_secret: ""
      server:
        - urls: 
          - "stun:stun.l.google.com:19302"
      client:
        - urls:
          - "stun:stun.l.google.com:19302"
        # - urls: "turn:demo.example.com:3478"
        #   username: "username"
        #   credential: "credential"
  bitstream:
    port: 1989
    game_path: ./rom.gb
    url: http://localhost:1989
    websocket_url: ws://localhost:1989/stream
    use_https: false
    full_picture_interval: 1000
    debug: true
    client_write_timeout: 5000
    rate_limit:
      ms: 100
      burst: 8