FROM golang:latest as build
MAINTAINER Lovis König <lovis@outlook.com>

WORKDIR /src
RUN git clone https://github.com/lvskng/gameboy.live.git
WORKDIR /src/gameboy.live
RUN git checkout dev
RUN git pull

#Install build dependencies
RUN apt update
RUN apt install -y libasound2-dev
WORKDIR /src/gameboy.live

RUN go get .
RUN go build -o /gbdotlive/app ./main-cli.go
RUN mkdir -p /gbdotlive/data
RUN mkdir -p /gbdotlive/client
RUN mv ./config.yaml /gbdotlive/data/
RUN mv ./client/ /gbdotlive/

FROM debian:bookworm-slim as final
WORKDIR /gbdotlive
COPY --from=build /gbdotlive/ /gbdotlive/
RUN apt update
RUN apt install -y libasound2
EXPOSE 1989
VOLUME /gbdotlive/rom
VOLUME /gbdotlive/config.yaml
CMD if ! [ -e /gbdotlive/data/rom.gb ]; then echo 'No rom.gb file found. Exiting.'; else /gbdotlive/app -l -r /gbdotlive/data/rom.gb; fi
